---
# tasks file for roles/imbicile.zabbix-agent

- name: create zabbix group
  group:
    name: "{{ zabbix_agent_group }}"
    system: true
    state: present

- name: create zabbix system user
  user:
    name: "{{ zabbix_agent_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ zabbix_agent_group }}"
    createhome: false

- name: create conf directory
  file:
    path: "/etc/zabbix-agent/"
    state: directory
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: 0755

- name: create log directory
  file:
    path: "{{ zabbix_agent_log }}"
    state: directory
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: 0755

- name: create tmp directory
  file:
    path: "/tmp/zabbix_agent_{{ zabbix_agent_version }}"
    state: directory

- name: download {{ zabbix_agent_package }}
  get_url:
    url: "{{ zabbix_agent_url }}"
    dest: "/tmp/{{ zabbix_agent_package }}"

- name: extract {{ zabbix_agent_package }}
  unarchive:
    copy: false
    src: "/tmp/{{ zabbix_agent_package }}"
    dest: "/tmp/zabbix_agent_{{ zabbix_agent_version }}"
    creates: "/tmp/zabbix_agent_{{ zabbix_agent_version }}/conf"

- name: copy system binaries
  copy:
    remote_src: yes
    src: "/tmp/zabbix_agent_{{ zabbix_agent_version }}/sbin/zabbix_agentd"
    dest: "/usr/local/bin/zabbix_agentd"
    mode: 0755
    owner: root
    group: root
  notify: restart zabbix-agent

- name: copy tools
  copy:
    remote_src: yes
    src: "/tmp/zabbix_agent_{{ zabbix_agent_version }}/bin/{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0644
    owner: root
    group: root
  with_items:
    - zabbix_get
    - zabbix_sender

- name: copy conf
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix-agent/zabbix-agent.conf"
    mode: 0644
  notify: restart zabbix-agent

- name: copy daemon script
  template:
    src: zabbix-agent.service.j2
    dest: "/etc/systemd/system/zabbix-agent.service"
    mode: 0644
  notify: restart zabbix-agent

- name: start and enable daemon
  systemd:
    daemon_reload: true
    name: zabbix-agent
    state: started
    enabled: true
